# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_TOUCHSCREEN_OPLUS) += util_interface/
obj-$(CONFIG_TOUCHSCREEN_OPLUS) += touchpanel_common_driver.o touchpanel_prevention.o touchpanel_healthinfo.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS) += Synaptics/
