# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_MACH_OPLUS) += oplus_devinfo/
obj-$(CONFIG_MACH_OPLUS) += oplus_mdmrst/
obj-$(CONFIG_MACH_OPLUS) += oplus_project/
obj-$(CONFIG_MACH_OPLUS) += project_info/
