# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_S3706) += S3706/
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS) += synaptics_touch_panel_remote.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS) += synaptics_common.o
